"""user code added in api log

Revision ID: 0466e06c146c
Revises: 730ccf903ceb
Create Date: 2025-06-27 21:43:01.299407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0466e06c146c'
down_revision = '730ccf903ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_logs', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('api_logs', sa.Column('user_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_logs', 'user_type')
    op.drop_column('api_logs', 'user_id')
    # ### end Alembic commands ###
