"""out of stock added

Revision ID: 23a50f1a6d19
Revises: 50f977d71418
Create Date: 2025-06-28 16:14:03.965211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a50f1a6d19'
down_revision = '50f977d71418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vegetables', sa.Column('is_out_of_stock', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vegetables', 'is_out_of_stock')
    # ### end Alembic commands ###
