"""quantity added in cart

Revision ID: 4149ba8021d3
Revises: 23a50f1a6d19
Create Date: 2025-06-28 18:50:21.183202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4149ba8021d3'
down_revision = '23a50f1a6d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'quantity')
    # ### end Alembic commands ###
