"""otp added in order

Revision ID: 50f977d71418
Revises: 0466e06c146c
Create Date: 2025-06-27 22:45:00.504302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f977d71418'
down_revision = '0466e06c146c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('otp', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'otp')
    # ### end Alembic commands ###
