"""status added

Revision ID: b486bb9401c0
Revises: 56412df9ee0f
Create Date: 2025-07-03 10:39:16.089545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b486bb9401c0'
down_revision = '56412df9ee0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_users', 'otp',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
    op.alter_column('customers', 'otp',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
    op.add_column('orders', sa.Column('payment_type', sa.String(length=36), server_default='COD', nullable=False))
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', mysql.ENUM('pending', 'offline_paid'), nullable=False))
    op.drop_column('orders', 'payment_type')
    op.alter_column('customers', 'otp',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
    op.alter_column('admin_users', 'otp',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
    # ### end Alembic commands ###
