"""uniqu removed2

Revision ID: c8a1f93119e4
Revises: dafc31209b70
Create Date: 2025-07-04 22:50:03.305806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a1f93119e4'
down_revision = 'dafc31209b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='admin_users')
    op.drop_index('email', table_name='customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'customers', ['email'], unique=True)
    op.create_index('email', 'admin_users', ['email'], unique=True)
    # ### end Alembic commands ###
