"""uniqu removed

Revision ID: dafc31209b70
Revises: b486bb9401c0
Create Date: 2025-07-04 22:48:38.614023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafc31209b70'
down_revision = 'b486bb9401c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='delivery_guys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'delivery_guys', ['email'], unique=True)
    # ### end Alembic commands ###
